name: Update JSON File

on:
  schedule:
    - cron: '0 0 * * 0' # This schedules the action to run at 00:00 UTC every Sunday. Adjust as needed.

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0' 
      
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('dplyr', 'tidyr', 'jsonlite', 'devtools'), dependencies = TRUE)"
        Rscript -e "devtools::install_github('JECDems/JECTools')"
        
    - name: Run convertToJson.R script
      run: Rscript R/convertToJson.R 
      
    - name: Commit changes
      run: |
        git config --global user.name 'Alfredo Romero'
        git config --global user.email 'Alfredo_Romero@jec.senate.gov'
        git add unemployment.JSON
        git commit -m 'Update unemployment JSON file' || echo "No changes to commit"
        git push
