name: Update JSON File

on:
  schedule:
    - cron: '00 15 * * 1-5' # 10:00 AM EST on weekdays
    - cron: '00 02 * * 1-5' # 10:00 PM EST on weekdays
  workflow_dispatch:
  
jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0' 
      
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::dplyr
          any::tidyr
          any::jsonlite
          any::fredr
          
    - name: Create and populate .Renviron file
      run: echo "FRED_API_KEY = '${{ secrets.FRED_API_KEY }}'" >> .Renviron
        
    - name: Run convertToJson.R script
      run: Rscript R/convertToJson.R 
      
    - name: Run convertToJsonInflation.R script
      run: Rscript R/convertToJsonInflation.R 
      
    - name: Commit changes
      run: |
        git config --global user.name 'Alfredo Romero'
        git config --global user.email 'Alfredo_Romero@jec.senate.gov'
        git add unemploymentActions.JSON InflationActions.JSON
        git commit -m 'Update unemployment and inflationJSON file' || echo "No changes to commit"
        git push
