name: Update JSON File

on:
  schedule:
    - cron: '15 18 * * 4' # This schedules the action to run at 17:30 UTC on Thursdays.
  workflow_dispatch: # This line enables manual trigger for the workflow.
    
jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0' 
      
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::dplyr
          any::tidyr
          any::jsonlite
          any::fredr
          
    - name: Create and populate .Renviron file
        run: |
          echo FRED_API_KEY="$FRED_API_KEY" >> ~/.Renviron
          shell: bash
        
    - name: Run convertToJson.R script
      run: Rscript R/convertToJson.R 
      
    - name: Commit changes
      run: |
        git config --global user.name 'Alfredo Romero'
        git config --global user.email 'Alfredo_Romero@jec.senate.gov'
        git add unemploymentActions.JSON
        git commit -m 'Update unemployment JSON file' || echo "No changes to commit"
        git push
